CREATE TABLE JAVA_MEMBER(
    NO NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(20),
    USERID VARCHAR2(30) NOT NULL UNIQUE,
    USERPW VARCHAR2(16) NOT NULL,
    TEL VARCHAR2(13)
    );
    
DROP SEQUENCE JAVA_MEMBER_SEQ; --생성할 시퀀스가 이미 존재한다면 삭제해준다
CREATE SEQUENCE JAVA_MEMBER_SEQ 
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
    
select * from java_member;